### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by ivanz5**
- general formatting (detect expressions, put them in normal style)
- indents
- spaces
- config file parsing

### CODE REVIEW

**Comment by Futurer** [comment]
Input:
----------
    public static void rectangle(int n, int m) {
        // printing of rectangle

        System.out.print("\n------------------------------------\n");
        System.out.print("\nRectangle:\n\n");

        // n - height of rectangle
        // m - width of rectangle

        for (int i = 0; i < n; i++) {
            for (int j = 0; j < m; j++) {

                // printing of longest sides of rectangle
                if ((i == 0) || (i == n - 1)) {
                    System.out.print("* ");
                } else {

                    // printing of short sides of rectangle
                    if ((j == 0) || (j == m - 1)) {
                        System.out.print("* ");
                    } else {
                        System.out.print("  ");
                    }
                }
            }
            System.out.print("\n");
        }

    }

-----


output:
---------
    public static void rectangle(int n, int m) {
        / /printing of rectangle System.out.print ("\n------------------------------------\n");
        System.out.print ("\nRectangle:\n\n");

        / /n -  height of rectangle / /m -  width of rectangle for (int i = 0;i < n;i++) {
            for (int j = 0;j < m;j++) {

                / /printing of longest sides of rectangle if ((i == 0)||(i == n -  1)) {
                    System.out.print (" * ");
                } else {

                    / /printing of short sides of rectangle if ((j == 0)||(j == m -  1)) {
                        System.out.print (" * ");
                    } else {

                        System.out.print (" ");
                    }
                }
            }
            System.out.print ("\n");
        }

    }

--------

????

**Comment by Futurer** [comment]
Where is an ability to create new formatting templates?

**Comment by ivanz5** [comment]
> Where is an ability to create new formatting templates?

Formatting templates are created by writing config file. Changing of config file path is not implemented yet. I will do it tomorrow and write a readme how to create and apply config.

**Comment by ivanz5** [comment]
@Futurer Comments handling is also not implemented at this moment.

**Pull request merged**
